apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-frontend
  name: user-frontend
  namespace: public
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
      - image: shreeda/major-frontend:latest
        name: user-frontend
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
---

apiVersion: v1
kind: Service
metadata:
  name: user-frontend
  namespace: public
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: user-frontend

---


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-frontend
  namespace: public
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  tls:  
  - hosts:
    -  "frontend.ragnarok.rocks"
    secretName: user-frontend
  rules:
  - host: "frontend.ragnarok.rocks"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-frontend
            port:
              number: 3000
